export const DEFAULT_PAYMENT_EXPIRY_MINUTES = 60;

export const DEFAULT_PAYMENT_SESSION_HOURS = 1;

export const MIN_PAYMENT_EXPIRY_MINUTES = 5;

export const PLACEHOLDER_PRICING_PAYMENT_AMOUNT = "0.0000001";
